# Generated by Django 3.1 on 2020-10-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
